[package]
name = "MDE310R"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libudev-sys = "0.1.4"
gilrs = "0.10.5"
rppal = "0.17.1"